import { getVersion } from '@tauri-apps/api/app';
import { platform, version as osVersion, arch } from '@tauri-apps/plugin-os';
import { invoke } from '@tauri-apps/api/core';

export interface CrashReportData {
  errorMessage: string;
  errorStack?: string;
  componentStack?: string;
  appVersion: string;
  platform: string;
  osVersion: string;
  architecture: string;
  currentModel: string | null;
  deviceId: string;
  timestamp: string;
}

export async function gatherCrashReportData(
  error: Error,
  componentStack?: string,
  currentModel?: string | null
): Promise<CrashReportData> {
  // Get async values
  const [appVer, deviceId] = await Promise.all([
    getVersion().catch(() => 'Unknown'),
    invoke<string>('get_device_id').catch(() => 'Unknown'),
  ]);

  // Get sync values from OS plugin (these are not promises)
  let os = 'Unknown';
  let osVer = 'Unknown';
  let architecture = 'Unknown';

  try {
    os = platform();
    osVer = osVersion();
    architecture = arch();
  } catch (e) {
    console.error('Failed to get OS info:', e);
  }

  return {
    errorMessage: error.message || 'Unknown error',
    errorStack: error.stack,
    componentStack: componentStack,
    appVersion: appVer,
    platform: os,
    osVersion: osVer,
    architecture,
    currentModel: currentModel || null,
    deviceId,
    timestamp: new Date().toISOString(),
  };
}

export function generateGitHubIssueUrl(data: CrashReportData): string {
  const repo = 'moinulmoin/voicetypr';
  const title = `[Crash Report] ${truncate(data.errorMessage, 80)}`;

  const body = `## Crash Report

**Error Message:**
\`\`\`
${data.errorMessage}
\`\`\`

**Stack Trace:**
\`\`\`
${truncate(data.errorStack || 'No stack trace available', 2000)}
\`\`\`

${data.componentStack ? `**Component Stack:**
\`\`\`
${truncate(data.componentStack, 1000)}
\`\`\`

` : ''}## Environment

| Property | Value |
|----------|-------|
| App Version | ${data.appVersion} |
| Platform | ${data.platform} |
| OS Version | ${data.osVersion} |
| Architecture | ${data.architecture} |
| Current Model | ${data.currentModel || 'None'} |
| Timestamp | ${data.timestamp} |

## Additional Context

<!-- Please add any additional context about the crash here -->
- What were you doing when the crash occurred?
- Can you reproduce this crash?
- Any other relevant information?

---
*This report was auto-generated by VoiceTypr crash reporter*
`;

  const params = new URLSearchParams({
    title,
    body,
    labels: 'bug,crash-report',
  });

  return `https://github.com/${repo}/issues/new?${params.toString()}`;
}

function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return str.slice(0, maxLength - 3) + '...';
}
